export enum Routes {
  Onboarding = "Onboarding",
  Auth = "AuthStack",
  MainBottomTab = "MainBottomTab",
  Intro = "Intro",
  Login = "Login",
  SignUp = "SignUp",
  ForgotPassword = "ForgotPassword",
  ResetPassword = "ResetPassword",
  Home = "Home",
  Search = "Search",
  Favourites = "Favourites",
  Settings = "Settings",
  EditProfile = "EditProfile",
  Movie = "Movie",
  PopularScreen = "PopularScreen",
}
